name: Listen Trigger
on:
  workflow_dispatch:
    inputs:
      pr_commit_sha:
        description: "Commit Id"
        required: false
  repository_dispatch:
    types: [listen]


jobs:
  listener-work:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    steps:
    - uses: hmarr/debug-action@v2
    
    - name: Dispatch Build Success
      run: |
        echo "Yes1"
