name: Listen Trigger
on:
  repository_dispatch:
    types: [listen]

jobs:
  listener-work-2:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Dispatch Build Success
      run: |
        echo "Yes2"