name: Trigger Workflow
on:
  push:

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Publish Repo Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{secrets.TEST_TOKEN}}
        event-type: listen
        client-payload: '{"pr_commit_sha":"1010"}'

    # - name: Dispatch Build Success
    #   uses: benc-uk/workflow-dispatch@v1
    #   with:
    #     ref: "refs/heads/master"
    #     token: ${{secrets.TEST_TOKEN}}
    #     workflow: Listen Trigger
    #     inputs: '{"pr_commit_sha":"100"}'

  fetch-docker-details:
    runs-on: [ubuntu-latest]
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v2
        with:
          ref: test1

      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2yaml
        with:
          path: '.github/dockerMeta/dockerDetails.yml'
          from: 'yaml'
          to: 'yaml'
      
      - name: Print yaml2yaml result
        run: echo "${{ steps.yaml2yaml.outputs.data }}"

      - name: Print yaml2yaml result
        run: |
          echo "${{ steps.yaml2yaml.outputs.data.Values.IsDocker }}"

      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: json2yaml
        with:
          path: '.github/dockerMeta/dockerDetails.yml'
          from: 'yaml'
          to: 'json'
      
      - name: Print json2yaml result
        run: echo "${{ steps.json2yaml.outputs.data }}"

      - name: Print json2yaml result
        run: | 
          echo "${{ steps.json2yaml.outputs.data.Values.IsDocker }}"
  
  fetch-using-shyaml: 
    runs-on: ubuntu-latest
    container:
      image: python:alpine3.12
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v2
        with:
          ref: test1
      
      - name: Fetch Release Name
        id: read-file
        run: |
          pip install shyaml
          details=$(cat .github/dockerMeta/dockerDetails.yml)
          echo "$(details | shyaml get-value IsDocker)"
          echo "$(details | shyaml get-value a)"
          echo "$(details | shyaml get-value b)"