name: Trigger Workflow
on:
  push:

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Publish Repo Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{secrets.TEST_TOKEN}}
        event-type: listen
        client-payload: '{"pr_commit_sha":"1010"}'

    # - name: Dispatch Build Success
    #   uses: benc-uk/workflow-dispatch@v1
    #   with:
    #     ref: "refs/heads/master"
    #     token: ${{secrets.TEST_TOKEN}}
    #     workflow: Listen Trigger
    #     inputs: '{"pr_commit_sha":"100"}'

  fetch-docker-details:
    runs-on: [ubuntu-latest]
    container:
      image: python:alpine3.12
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v2
        with:
          ref: test1

      - name: Fetch Release Name
        id: read-file
        run: |
          pip install pyyaml
          from fetch_docker_details import details
          details["IsDocker"]

