name: Trigger Workflow
on:
  push:

jobs:
  trigger-build:
    runs-on: ubuntu-latest 
    timeout-minutes: 2

    steps:
    - uses: hmarr/debug-action@v2
    
    - name: Publish Repo Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{secrets.TEST_TOKEN}}
        event-type: listen
        client-payload: '{"pr_commit_sha":"10s10"}'

    - name: Dispatch Build Success
      uses: benc-uk/workflow-dispatch@v1
      with:
        ref: "refs/heads/master"
        token: ${{secrets.TEST_TOKEN}}
        workflow: Listen Trigger
        inputs: '{"pr_commit_sha":"100"}'

        

