name: Trigger Workflow
on:
  push:

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Dispatch Build Success
      uses: benc-uk/workflow-dispatch@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        workflow: Listen Trigger
        inputs: '{"pr_commit_sha":"100"}'