name: Notification
on:
  workflow_run:
    workflows: 
      - .NET Core
      - Full Framework
      - Post Build Success
      - Trigger Workflow
    types: 
      - completed

jobs:
  notify-on-fail-test:
    if: ${{ github.event.workflow_run.head_branch }} == '$(echo ${GITHUB_REF#refs/heads/})' && github.event.workflow_run.conclusion == 'success' 
    runs-on: [ubuntu-latest]
    timeout-minutes: 2

    steps:
        - name: Notify on Build Failure
          uses: skitionek/notify-microsoft-teams@master
          with:
            webhook_url: https://philips.webhook.office.com/webhookb2/${{secrets.HOOK}}
            overwrite: "{title: `Build failed on master ${{github.repository}}`}"
            needs: ${{ toJson(needs) }}
            job: "{\"status\": \"failure\"}"
            steps: ${{ toJson(steps) }}
