# This workflow runs on completion of the 'workflows' listed
# If any of it "failed" on "master" it will send a teams notification
name: Notification
on:
  workflow_run:
    workflows: 
      - .NET Core
      - Full Framework
      - Post Build Success
      - Trigger Workflow
    types: 
      - completed

jobs:
  notify-on-fail-test:
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: [ubuntu-latest]
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v2
      
      - name: Build Failure Details
        run: |
          echo "Build Run - ${{github.event.workflow_run.html_url}}"
          echo "Build Failed on - ${{github.event.workflow_run.head_branch}}"
      
      - name: Determine default branch
        run: |
          DEFAULT_BRANCH=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
          echo "default_branch_ref=$DEFAULT_BRANCH" >> $GITHUB_ENV
      
      #- uses: hmarr/debug-action@v2
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.HOOK_URI }}
          raw: >-
            {
              "@type": "MessageCard",
              "@context": "http://schema.org/extensions",
              "title": "No ${variables} avaliable in here",
              "potentialAction": "[{'@context': 'http://schema.org',target: [`${repoUrl}/actions/runs/${runId}`], '@type': 'ViewAction', name: 'View Workflow Run'}]"
             }
  
      - name: Notify dedicated teams channel
        if: github.event.workflow_run.head_branch == env.default_branch_ref
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.HOOK_URI }}
          notification-summary: "Build Failure notification - ${{github.event.workflow_run.html_url}}" 
          notification-color: 17a2b8
          timezone: America/New_York
          
  notify-on-fail-test-val:
    runs-on: [ubuntu-latest]
    timeout-minutes: 2
    steps:
      
      - name: Print values
        run: |
          echo ${{github.event.workflow_run.head_branch}}
          echo ${GITHUB_REF#refs/heads/}
          echo ${{github.event.workflow_run.html_url}}
