name: Notification
on:
  workflow_run:
    workflows: 
      - .NET Core
      - Full Framework
      - Post Build Success
      - Trigger Workflow
    types: 
      - completed

jobs:
  notify-on-fail-test:
    if: github.event.workflow_run.conclusion == 'failure' #&& github.event.workflow_run.head_branch == '$(echo ${GITHUB_REF#refs/heads/})'
    runs-on: [ubuntu-latest]
    timeout-minutes: 2

    steps:  
      - name: Print event values
        run: |  
          echo ${{ github.event.workflow_run.conclusion }}
          echo ${{ github.event.workflow_run.head_branch }}
          echo ${GITHUB_REF#refs/heads/}
