# This workflow runs on completion of the 'workflows' listed
# If any of it "failed" on "master" it will send a teams notification
name: Notification
on:
  workflow_run:
    workflows: 
      - .NET Core
      - Full Framework
      - Post Build Success
      - Trigger Workflow
    types: 
      - completed

jobs:
  notify-on-fail-test:
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: [ubuntu-latest]
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v2
      
      - name: Build Failure Details
        run: |
          echo "Build Run - ${{github.event.workflow_run.html_url}}"
          echo "Build Failed on - ${{github.event.workflow_run.head_branch}}"
      
      - name: Determine default branch
        run: |
          DEFAULT_BRANCH=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
          echo "default_branch_ref=$DEFAULT_BRANCH" >> $GITHUB_ENV
      
      #- uses: hmarr/debug-action@v2
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.HOOK_URI }}
          raw: |
              { 
                "@type": "MessageCard",
                "@context": "http://schema.org/extensions",
                "title": "No x avaliable in here"
              }
              
      - name: Microsoft Teams Notification22
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.HOOK_URI }}
          raw: >-
            {
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    "themeColor": "0076D7",
    "summary": "Larry Bryant created a new task",
    "sections": [{
        "activityTitle": "Larry Bryant created a new task",
        "activitySubtitle": "On Project Tango",
        "activityImage": "https://teamsnodesample.azurewebsites.net/static/img/image5.png",
        "facts": [{
            "name": "Assigned to",
            "value": "Unassigned"
        }, {
            "name": "Due date",
            "value": "Mon May 01 2017 17:07:18 GMT-0700 (Pacific Daylight Time)"
        }, {
            "name": "Status",
            "value": "Not started"
        }],
        "markdown": true
    }],
    "potentialAction": [{
        "@type": "ActionCard",
        "name": "Add a comment",
        "inputs": [{
            "@type": "TextInput",
            "id": "comment",
            "isMultiline": false,
            "title": "Add a comment here for this task"
        }],
        "actions": [{
            "@type": "HttpPOST",
            "name": "Add comment",
            "target": "https://docs.microsoft.com/outlook/actionable-messages"
        }]
    }, {
        "@type": "ActionCard",
        "name": "Set due date",
        "inputs": [{
            "@type": "DateInput",
            "id": "dueDate",
            "title": "Enter a due date for this task"
        }],
        "actions": [{
            "@type": "HttpPOST",
            "name": "Save",
            "target": "https://docs.microsoft.com/outlook/actionable-messages"
        }]
    }, {
        "@type": "OpenUri",
        "name": "Learn More",
        "targets": [{
            "os": "default",
            "uri": "https://docs.microsoft.com/outlook/actionable-messages"
        }]
    }, {
        "@type": "ActionCard",
        "name": "Change status",
        "inputs": [{
            "@type": "MultichoiceInput",
            "id": "list",
            "title": "Select a status",
            "isMultiSelect": "false",
            "choices": [{
                "display": "In Progress",
                "value": "1"
            }, {
                "display": "Active",
                "value": "2"
            }, {
                "display": "Closed",
                "value": "3"
            }]
        }],
        "actions": [{
            "@type": "HttpPOST",
            "name": "Save",
            "target": "https://docs.microsoft.com/outlook/actionable-messages"
        }]
    }]
}
              
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.HOOK_URI }}
          raw: "{\"@type\": \"MessageCard\", \"@context\": \"http://schema.org/extensions\", \"title\": \"No x avaliable in here\" }"

  
      - name: Notify dedicated teams channel
        if: github.event.workflow_run.head_branch == env.default_branch_ref
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.HOOK_URI }}
          notification-summary: "Build Failure notification - ${{github.event.workflow_run.html_url}}" 
          notification-color: 17a2b8
          timezone: America/New_York
          
  notify-on-fail-test-val:
    runs-on: [ubuntu-latest]
    timeout-minutes: 2
    steps:
      
      - name: Print values
        run: |
          echo ${{github.event.workflow_run.head_branch}}
          echo ${GITHUB_REF#refs/heads/}
          echo ${{github.event.workflow_run.html_url}}
