name: Notification
on:
  workflow_run:
    workflows: 
      - .NET Core
      - Full Framework
      - Post Build Success
      - Trigger Workflow
    types: 
      - completed

jobs:
  notify-on-fail-test:
#     if: |
#       (${{ github.event.workflow_run.head_branch == '$(echo ${GITHUB_REF#refs/heads/})' &&
#       github.event.workflow_run.conclusion == 'failure' }})
    
    runs-on: [ubuntu-latest]
    timeout-minutes: 2
    env:
      DEFAULT_BRANCH: ${{ ${GITHUB_REF#refs/heads/} }}
      
    if: |
      always() &&
      (github.event.workflow_run.conclusion == 'success') && 
      (github.event.workflow_run.head_branch == '{{ env.DEFAULT_BRANCH }}')
    
    steps:
        - name: Notify on Build Failure
          uses: skitionek/notify-microsoft-teams@master
          with:
            webhook_url: ${{secrets.HOOK_URI}}
            overwrite: "{title: `Build failed on master ${{github.repository}}`}"
            needs: ${{ toJson(needs) }}
            job: "{\"status\": \"failure\"}"
            steps: ${{ toJson(steps) }}
            
        - name: Notify dedicated teams channel
          uses: jdcargile/ms-teams-notification@v1.3
          with:
            github-token: ${{ github.token }} # this will use the runner's token.
            ms-teams-webhook-uri: ${{ secrets.HOOK_URI }}
            notification-summary: Build Failure notification 
            notification-color: 17a2b8
            timezone: America/New_York

  notify-on-fail-test-val:
    runs-on: [ubuntu-latest]
    timeout-minutes: 2
    env:
      DEFAULT_BRANCH: ${GITHUB_REF#refs/heads/}
    steps:
      - name: Print values
        run: |
          echo ${{github.event.workflow_run.head_branch}}
          echo ${GITHUB_REF#refs/heads/}
          echo ${{github.event.workflow_run.conclusion}}
          echo ${{git remote show origin | awk '/HEAD branch/ {print $NF}' }}
          echo ${{ github.event.workflow_run.head_branch== '{{ env.DEFAULT_BRANCH }}' }}
            
  
